export const styles = {
    bgContainer:{
        display:'flex',
        flexDirection:'column',
        alignItems: 'center',
        justifyContent: 'center',        
        minHeight: '100vh',
        padding:'10px',
        gap:2
    },
    contentContainer:{
        backgroundColor:'#fff',
        border:'1px solid #c8c8c8',
        borderRadius:'10px',
        height:'550px',
        width:'420px',
    },
    resultContainer:{        
       borderBottom: '1px solid #c8c8c8',
       height:'30%',
       fontSize: '50px',
       display: 'flex',
       flexDirection:'column',
       alignItems: 'center',
       justifyContent: 'space-between',
       width:'100%',
    },
    resultInputContainer:{
        width:'100%',
        padding: '20px',
        display: 'flex',
        alignItems: 'center',
    },
    numsInput:{
        border:'none',
        outline:'none',
        fontSize: '50px',
        width:'91%',
    },
    result:{
        fontSize:'50px',
        height:'50px',
        width:'90%',
        padding:'10px 20px',
        alignSelf:'flex-end',
        borderTop:'1px solid #c8c8c8',
    },

    inputContainer:{
        display:'flex',
        flexWrap: 'wrap',
        padding: '20px',
        gap:2
    },
    numButton:{
        height:'50px',        
        minWidth: '40px',
        width:'80px',
        maxWidth: '100%',
        fontSize:'20px',
        cursor:'pointer',
        outline:'none',
        border:'none',
        borderRadius:'50%',
        backgroundColor:'#f7f9fa',
    },
    spclButton:{
        height:'50px',        
        minWidth: '40px',
        width:'80px',
        maxWidth: '100%',
        fontSize:'20px',
        cursor:'pointer',
        outline:'none',
        border:'none',
        borderRadius:'50%',
        backgroundColor:'#edf8ff',
        color:'#1976d2',
    },
    equalButton:{
        height:'50px',        
        minWidth: '40px',
        width:'80px',
        maxWidth: '100%',
        fontSize:'20px',
        cursor:'pointer',
        outline:'none',
        border:'none',
        borderRadius:'50%',
        backgroundColor:'#1976d2',
        color:'#fff',
    },
    eachRow:{
        display:'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        gap:2
    },
   
}